/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103X6.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_UART_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include "Stm32_F103C6_RCC_driver.h"
#include "Ultrasonic_Sensor.h"
#include "Collision_Avoidance.h"

void Clock_init()
{
	// GPIO init
	RCC_GPIOA_CLK_EN();
	RCC_AFIO_CLK_EN();
	// USART1
	RCC_USART1_CLK_EN();

}


int main(void)
{
	Clock_init();
	HAL_US_Init(Serial_Passive_Mode, USART1);


    /* Loop forever */
	while(1)
	{
		APP_FCA_Detecte_Collision_Status();
	}
}
